### ISSUE TITLE
Move from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/idris#126]
This repo is currently using Travis, but we have standardized on GitHub actions. 
This is an example workflow to build from: https://github.com/exercism/generic-track/blob/main/.github/workflows/test.yml

**Comment by ErikSchierboom** [comment]
@keiravillekode Just in case you needed something more to work on, this issue would be great to fix :)

**Comment by keiravillekode** [comment]
The `.travis.yml` file dates back to when Idris 1 was being used. (Idris 1 was implemented in Haskell, Idris 2 is not.)

We can remove the file as [Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration) will need to be implemented again with Idris 2.

For reference, here is the essence of the `.travis.yml` file:

```
install:
  - bin/fetch-configlet
  - ...
  - bin/fetch-idris-testing.sh
  - idris --version

script:
  - bin/configlet lint .
  - bin/solve_exercises.sh
```

**Comment by ErikSchierboom** [comment]
👍  Basically, the "only" thing you'll need to do is to create a `.github/workflows/test.yml` workflow that calls the appropriate commands (configlet linting can be omitted, as the `configlet.yml` workflow takes care of it).

**Comment by keiravillekode** [comment]
Resolved by https://github.com/exercism/idris/pull/189
