### ISSUE TITLE
Failing tests are not expressive

### ISSUE THREAD

**Issue by NobbZ** [exercism/idris#20]
I am trying to do `leap` and implemented it as ``leap y = isLeap year = (y `mod` 4) == 0`` as a first step. running the tests result in the following output:

```plain
% idris --testpkg Leap.ipkg
Entering directory `./src'
Type checking ./Test/Leap.idr
Type checking /tmp/idris1315634022635723058.idr
Test Passed
Test Passed
Test Failed
Test Passed
Leaving directory `./src'
```

It would be nice if a failing test could give us some more information about what kind of test it was. This way I have to try to read the testfiles, figure out which test is actually the third, hoping that execution order was not randomized, and then I have to understand the test.

**Comment by yurrriq** [comment]
We should use idris-testing or similar with descriptive labels. Remind me if I don't past a link and lay out a plan in the next couple days?

**Comment by NobbZ** [comment]
I've put this on "remind me next weekend" in my inbox.

**Comment by yurrriq** [comment]
Here's [idris-testing](https://github.com/jfdm/idris-testing) for a start.
