### ISSUE TITLE
Consider Specdris

### ISSUE THREAD

**Issue by yurrriq** [exercism/idris#43]
Since [idris-testing](https://github.com/jfdm/idris-testing) is archived, consider using [Specdris](https://github.com/pheymann/specdris).

**Comment by NobbZ** [comment]
I'm not aware of any alternatives…

Also I have to admit, I'm not very good in idiomatic Idris… I use it more like a strict haskell ;)

If I use it at all ;)

In theory, it should be possible to write "tests" in a way that the program does not even compile unless the implementation is correct. The coq track does it already that way. Can we move towards such a system with idris as well?

PS: Sorry for high latency, I'm trying to catch up with my inbox again ;)

**Comment by yurrriq** [comment]
We can write such "tests" where the "test" is basically the type signature and the implementation is usually just `Refl`. Unit tests can be helpful too/instead. I don't have strong feelings atm about which direction to take here... Specdris is better than the orphaned idris-test though imo.
